name: devkitflutter
description: Flutter UI Kit - Developer Kit

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 11.0.0+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  battery_plus: ^2.1.4
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  #charts_flutter: 0.11.0
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  cloud_firestore: ^3.1.17
  convex_bottom_bar: 3.0.0
  cupertino_icons: 1.0.3
  date_format: 2.0.4
  device_info_plus: 2.2.0
  dio: 4.0.0
  fab_circular_menu: 1.0.2
  firebase_auth: 3.1.2
  firebase_storage: 10.0.4
  fluttertoast: 8.0.8
  flutter_barcode_scanner: 2.0.0
  flutter_bloc: ^8.0.1
  flutter_html: 2.1.4 # this package has webview_flutter plugins
  flutter_local_notifications: 8.2.0 # for ios: if using xcode version 11, you must use version ^4.0.1+2, but we recomended to using the latest xcode version
  flutter_native_timezone: 2.0.0
  flutter_signature_pad: 3.0.0
  flutter_spinkit: 5.1.0
  flutter_staggered_grid_view: 0.4.0
  flutter_typeahead: 3.2.1
  geocoding: 2.0.1
  google_fonts: 2.1.0
  google_maps_flutter: 2.0.11
  google_maps_flutter_web: 0.3.2
  google_sign_in: 5.1.1
  image: 3.0.8
  image_cropper: 1.4.1
  image_picker: 0.8.0+4
  intl: 0.17.0
  package_info_plus: 1.2.1
  path_provider: 2.0.5
  permission_handler: 7.2.0 # for ios: if using xcode version 11, you must use version 5.0.1+2 without caret symbol (^), but we recomended to using the latest xcode version
  photofilters: 3.0.1
  pin_code_fields: 7.3.0
  share_plus: 2.2.0
  shared_preferences: 2.0.8
  shimmer: 2.0.0
  signature: 4.1.1
  sliding_up_panel: 2.0.0+1
  timeline_tile: 2.0.0
  universal_io: 2.0.4
  url_launcher: 6.0.12
  uuid: 3.0.5
  waterfall_flow: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/google_fonts/Audiowide-Regular.ttf
    - family: Bariol
      fonts:
        - asset: assets/fonts/Bariol_Regular.otf
        - asset: assets/fonts/Bariol_Thin.otf
          weight: 100
        - asset: assets/fonts/Bariol_Thin_Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Bariol_Light.otf
          weight: 300
        - asset: assets/fonts/Bariol_Light_Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Bariol_Bold.otf
          weight: 700

  assets:
  - assets/images/logo_light.png
  - assets/images/logo_dark.png
  - assets/images/logo_horizontal.png
  - assets/images/lamp.jpg
  - assets/images/google.png
  - assets/images/facebook.png
  - assets/images/twitter.png
  - assets/images/whatsapp.png
  - assets/images/placeholder.jpg
  - assets/images/visa.png
  - assets/images/mastercard.png
  - assets/images/direction.png
  - assets/images/stop.png

  - assets/images/lang/en.png
  - assets/images/lang/id.png
  - assets/images/lang/ar.png
  - assets/images/lang/zh.png
  - assets/images/lang/hi.png
  - assets/images/lang/th.png
  - assets/images/lang/tk.png

  - assets/images/apps/food_delivery/logo.png
  - assets/images/apps/ecommerce/logo.png
  - assets/images/apps/ecommerce/onboarding/search_product.gif

  - assets/lang/en.json
  - assets/lang/id.json
  - assets/lang/ar.json
  - assets/lang/zh.json
  - assets/lang/hi.json
  - assets/lang/th.json
  - assets/lang/tk.json

  - assets/html/webview.html